#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-typed_ast
Version  : 1.5.1
Release  : 51
URL      : https://files.pythonhosted.org/packages/39/ea/548f05abe9604a08ae99c64bf75a4061a4eb9b0062162501bfb4fafdf68f/typed_ast-1.5.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/39/ea/548f05abe9604a08ae99c64bf75a4061a4eb9b0062162501bfb4fafdf68f/typed_ast-1.5.1.tar.gz
Summary  : a fork of Python 2 and 3 ast modules with type comment support
Group    : Development/Tools
License  : Apache-2.0
Requires: pypi-typed_ast-license = %{version}-%{release}
Requires: pypi-typed_ast-python = %{version}-%{release}
Requires: pypi-typed_ast-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
# Typed AST
[![Build Status](https://travis-ci.org/python/typed_ast.svg?branch=master)](https://travis-ci.org/python/typed_ast)
[![Chat at https://gitter.im/python/typed_ast](https://badges.gitter.im/python/typed_ast.svg)](https://gitter.im/python/typed_ast)

%package license
Summary: license components for the pypi-typed_ast package.
Group: Default

%description license
license components for the pypi-typed_ast package.


%package python
Summary: python components for the pypi-typed_ast package.
Group: Default
Requires: pypi-typed_ast-python3 = %{version}-%{release}

%description python
python components for the pypi-typed_ast package.


%package python3
Summary: python3 components for the pypi-typed_ast package.
Group: Default
Requires: python3-core
Provides: pypi(typed_ast)

%description python3
python3 components for the pypi-typed_ast package.


%prep
%setup -q -n typed_ast-1.5.1
cd %{_builddir}/typed_ast-1.5.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641598332
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-typed_ast
cp %{_builddir}/typed_ast-1.5.1/LICENSE %{buildroot}/usr/share/package-licenses/pypi-typed_ast/5cba2695438a74e1f7a057b4fe6ec39bc444a0fc
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-typed_ast/5cba2695438a74e1f7a057b4fe6ec39bc444a0fc

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
