#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : typed-ast
Version  : 1.2.0
Release  : 16
URL      : https://files.pythonhosted.org/packages/00/be/c3769a5d6a179c42eba04186dc7efeb165edf92f7b1582ccfe81cb17d7f9/typed-ast-1.2.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/00/be/c3769a5d6a179c42eba04186dc7efeb165edf92f7b1582ccfe81cb17d7f9/typed-ast-1.2.0.tar.gz
Summary  : a fork of Python 2 and 3 ast modules with type comment support
Group    : Development/Tools
License  : Apache-2.0
Requires: typed-ast-license = %{version}-%{release}
Requires: typed-ast-python = %{version}-%{release}
Requires: typed-ast-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
# Typed AST
[![Build Status](https://travis-ci.org/python/typed_ast.svg?branch=master)](https://travis-ci.org/python/typed_ast)
[![Chat at https://gitter.im/python/typed_ast](https://badges.gitter.im/python/typed_ast.svg)](https://gitter.im/python/typed_ast)

%package license
Summary: license components for the typed-ast package.
Group: Default

%description license
license components for the typed-ast package.


%package python
Summary: python components for the typed-ast package.
Group: Default
Requires: typed-ast-python3 = %{version}-%{release}

%description python
python components for the typed-ast package.


%package python3
Summary: python3 components for the typed-ast package.
Group: Default
Requires: python3-core

%description python3
python3 components for the typed-ast package.


%prep
%setup -q -n typed-ast-1.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1547772356
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/typed-ast
cp LICENSE %{buildroot}/usr/share/package-licenses/typed-ast/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/typed-ast/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
